### ISSUE TITLE
Can not reproduce your work

### ISSUE THREAD

**Issue by BCeZn** [weiT1993/CutQC#2]
When I want to repeat your work, I find that your code doesn't work. When I looked for the problem, I found the following problems:
In your file "example.py"  line 12 "from qiskit_helper_functions.non_ibmq_functions import generate_circ",but I found that function "generate_circ is in qiskit_helper_functions/benchmarks.py.
And you passed 3 arguments to the function generate_circ, but the function generate_circ expects 5 arguments.
Your work is excellent and I hope you can fix your code so we can learn.

**Comment by weiT1993** [comment]
Thanks for bringing up the code synchronization issue. I will try to make the repo more self-contained to reduce external dependencies.

**Comment by weiT1993** [comment]
I've localized the helper functions. Please try again.

**Comment by weiT1993** [comment]
Closing this since I have not heard any more questions.
